# Generated by Django 2.1.5 on 2019-01-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_convite'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='contados',
            field=models.ManyToManyField(related_name='_perfil_contados_+', to='perfis.Perfil'),
        ),
    ]
