# Generated by Django 2.1.5 on 2019-01-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_perfil_contados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='contados',
        ),
        migrations.AddField(
            model_name='perfil',
            name='contatos',
            field=models.ManyToManyField(related_name='_perfil_contatos_+', to='perfis.Perfil'),
        ),
    ]
